spring:
  application:
    name: shoebox
# DB 설정
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: springboot
    password: java1234

 # JPA 설정
  jpa:
    database: oracle
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# oauth2 registration
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: 7wLnmGoeogf6p9VxAmfb
            client-secret: EZqyPh69IE
            redirect-uri: http://localhost:8090/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email

          google:
            client-name: google
            client-id: 5181970466-bm2ia79bpf7vc6glrqagqj5hh54s1b9v.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8090/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

# MyBatis 설정
mybatis:
  type-aliases-package: com.test.thymeleaf.dto
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8090
